name: build

on:
  push:
  create:
  release:
    types: [published]
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Build on CMAke
        uses: threeal/cmake-action@v2.1.0